[package]
name = "petgraph-gen"
version = "0.1.2"
authors = ["Tapani Honkanen"]
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["graph", "graph-algorithms", "generator"]
categories = ["algorithms"]
description = "Graph generators for petgraph"
repository = "https://github.com/tapanih/petgraph-gen"
readme = "README.md"
documentation = "https://docs.rs/petgraph-gen"

[lib]
name = "petgraph_gen"

[dependencies]
petgraph = "0.8"
rand = "0.10"
rustc-hash = "2.1"

[dev-dependencies]
criterion = "0.8"
rand = "0.10"

[[bench]]
name = "benchmark"
harness = false
